trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: springbootapp
  acrName: proj5acr.azurecr.io
  imageTag: $(Build.BuildId)

steps:

# ======================
# Maven Build
# ======================
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true


# ======================
# Docker Build
# ======================
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: proj5acr.azurecr.io/springbootapp
    Dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)

# ======================
# Install Trivy + Scan
# ======================
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

    trivy image springbootapp:$(Build.BuildId)
  displayName: Trivy Scan


# ======================
# Docker Push
# ======================
- task: Docker@2
  displayName: Push Docker Image
  inputs:
    containerRegistry: 'acrservice-conn'
    command: push
    repository: springbootapp
    tags: |
      $(Build.BuildId)