trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  acrName: proj5acr.azurecr.io
  imageName: java-app
  imageTag: $(Build.BuildId)

steps:

# ======================
# Maven Build
# ======================
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true


# ======================
# Docker Build
# ======================
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    command: build
    repository: $(acrName)/$(imageName)
    Dockerfile: Dockerfile
    tags: |
      $(imageTag)


# ======================
# Trivy Scan
# ======================
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

    trivy image $(acrName)/$(imageName):$(imageTag)
  displayName: Trivy Scan


# ======================
# Docker Push
# ======================
- task: Docker@2
  displayName: Push Docker Image
  inputs:
    containerRegistry: 'acrservice-conn'
    command: push
    repository: $(imageName)
    tags: |
      $(imageTag)
